In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import warnings
warnings.filterwarnings('ignore')

In [2]:
a=pd.read_csv(r'dataset/multi_hazard_india_dataset_with_events.csv')
a.head()

DateTime  Latitude  Longitude  SST(°C)  SeaLevel(cm)  \
0  2025-01-01 00:00:00     13.24      87.21    30.39          55.9   
1  2025-01-01 03:00:00      8.79      83.55    31.63          -9.9   
2  2025-01-01 06:00:00      9.95      76.67    28.20          40.2   
3  2025-01-01 09:00:00     14.31      72.21    31.65          52.0   
4  2025-01-01 12:00:00      8.48      86.55    27.55          62.9   

   Pressure(hPa)  WindSpeed(km/h)  Rainfall(mm/hr)  WaveHeight(m)  DO(mg/L)  \
0          985.5             23.4              2.9           7.00      6.01   
1         1014.7             92.6             30.6           0.55      3.12   
2         1007.5             30.0             25.7           4.94      3.23   
3          993.5              2.4             11.5           2.31      6.42   
4          990.9             78.0             27.3           1.89      7.85   

   SeismicMag     HazardLabel        EventCategory  
0         0.0         Cyclone  Hydrometeorological  
1         0.0  Sea-level Rise        Oceanographic  
2         0.0         Tsunami          Geophysical  
3         6.8           Storm  Hydrometeorological  
4         0.0       Pollution        Environmental

In [3]:
from sklearn.model_selection import train_test_split as tts
import functions as ff
ff.rs(a)


DateTime
--------
2025-05-05 21:00:00: 1              2025-01-01 06:00:00: 1              (Other)     : 994            
2025-01-01 00:00:00: 1              2025-01-01 09:00:00: 1              
2025-01-01 03:00:00: 1              2025-01-01 12:00:00: 1              

Latitude
--------
Min.        : 8.0            Median      : 15.2           3rd Qu.     : 18.51          
1st Qu.     : 11.97          Mean        : 15.16          Max.        : 21.98          

Longitude
---------
Min.        : 72.01          Median      : 80.23          3rd Qu.     : 83.98          
1st Qu.     : 76.22          Mean        : 80.14          Max.        : 87.97          

SST(°C)
-------
Min.        : 26.01          Median      : 29.05          3rd Qu.     : 30.43          
1st Qu.     : 27.52          Mean        : 28.97          Max.        : 31.99          

SeaLevel(cm)
------------
Min.        : -9.9           Median      : 44.65          3rd Qu.     : 71.8           
1st Qu.     : 16.98          Mean

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
a['HazardLabel']=le.fit_transform(a['HazardLabel'])
a['EventCategory']=le.fit_transform(a['EventCategory'])


In [5]:
a.head()

DateTime  Latitude  Longitude  SST(°C)  SeaLevel(cm)  \
0  2025-01-01 00:00:00     13.24      87.21    30.39          55.9   
1  2025-01-01 03:00:00      8.79      83.55    31.63          -9.9   
2  2025-01-01 06:00:00      9.95      76.67    28.20          40.2   
3  2025-01-01 09:00:00     14.31      72.21    31.65          52.0   
4  2025-01-01 12:00:00      8.48      86.55    27.55          62.9   

   Pressure(hPa)  WindSpeed(km/h)  Rainfall(mm/hr)  WaveHeight(m)  DO(mg/L)  \
0          985.5             23.4              2.9           7.00      6.01   
1         1014.7             92.6             30.6           0.55      3.12   
2         1007.5             30.0             25.7           4.94      3.23   
3          993.5              2.4             11.5           2.31      6.42   
4          990.9             78.0             27.3           1.89      7.85   

   SeismicMag  HazardLabel  EventCategory  
0         0.0            0              2  
1         0.0            3              3  
2         0.0            5              1  
3         6.8            4              2  
4         0.0            2              0

In [6]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
x=a.drop(columns=['HazardLabel','EventCategory','DateTime'])
y=a['HazardLabel']
y1=a['EventCategory']
xt,xte,yt,yte=tts(x,y,test_size=0.2,random_state=42)
xt1,xte1,yt1,yte1=tts(x,y1,test_size=0.2,random_state=42)
models=[KNeighborsClassifier(),RandomForestClassifier(),DecisionTreeClassifier(),LogisticRegression(max_iter=500),SVC(),GaussianNB(),GradientBoostingClassifier(),AdaBoostClassifier()] 
for model in models:
    model.fit(xt,yt)
    pred=model.predict(xte)
    print(model)
    print(accuracy_score(yte,pred))
    print(confusion_matrix(yte,pred))
    print(classification_report(yte,pred))
    print()
for model in models:
    model.fit(xt1,yt1)
    pred=model.predict(xte1)
    print(model)
    print(accuracy_score(yte1,pred))
    print(confusion_matrix(yte1,pred))
    print(classification_report(yte1,pred))
    print() 


KNeighborsClassifier()
0.165
[[10  2  1  2  3  5]
 [12  6  6  4  7  4]
 [ 7  1  6 10  5  3]
 [ 9  7  4  1  7  4]
 [ 7  8  6  2  7 12]
 [ 9  3  6  6  5  3]]
              precision    recall  f1-score   support

           0       0.19      0.43      0.26        23
           1       0.22      0.15      0.18        39
           2       0.21      0.19      0.20        32
           3       0.04      0.03      0.04        32
           4       0.21      0.17      0.18        42
           5       0.10      0.09      0.10        32

    accuracy                           0.17       200
   macro avg       0.16      0.18      0.16       200
weighted avg       0.16      0.17      0.16       200


RandomForestClassifier()
0.155
[[ 5  3  7  1  3  4]
 [ 5  3  6 11  7  7]
 [ 6  3 11  5  3  4]
 [ 5  5 10  4  4  4]
 [10  9  0  5  5 13]
 [ 7  3  7  4  8  3]]
              precision    recall  f1-score   support

           0       0.13      0.22      0.16        23
           1       0.12      0.08

In [9]:
import torch
import torch.nn as nn
mo=AdaBoostClassifier()
mo.fit(xt,yt)
mo.predict(xte)
torch.save(mo,'mo.pkl')